version: "3.9"

services: 
  app:
    container_name: app
    image: app_node:latest
    networks:
      - jenk_gitlab_net
      - node_compose
    environment:
      PORT: ${PORT}
  
  rev_prox:
    image: nginx:latest
    container_name: reverse_proxy
    networks:
      - node_compose
    ports:
      - 80:80
    restart: always
    volumes:
      - "${CONF_FILE_LOCATION}:/etc/nginx/conf.d/default.conf"

networks:
  jenk_gitlab_net:
    name: jenk_gitlab_net
    external: true
  node_compose:
    name: node_compose   